apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-edit
rules:
- apiGroups: [""]
  resources: ["pods","services","configmaps"]
  verbs: ["create","delete","get","watch","list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-computation
subjects:
- kind: ServiceAccount
  name: spark
roleRef:
  kind: Role
  name: spark-edit
  apiGroup: ""
